DELETE FROM T_UNDO;
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='PK_RA_ID',
	OPERATION='U',
	QUOTES='n',
	P_KEY='y',
	VALUE='1',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='A_USER',
	OPERATION='K',
	QUOTES='y',
	P_KEY='n',
	VALUE='arroyyol',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='n';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='AUTHORITY',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Article 15',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='COMMENT',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Reporting Obligation of Council Directive 94/67/EC on the incineration of hazardous waste will be repealed after 28/12/2005 by Directive 200/76/EC on the incineration of waste. The last report shall cover the three year period 2004-2006.',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='CONTINOUS_REPORTING',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='no',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='COORDINATOR',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Country contacts',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='COORDINATOR_ROLE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='eionet-nfp',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';

INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='COORDINATOR_ROLE_SUF',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='0',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='COORDINATOR_URL',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='http://www.pops.int/documents/implementation/nips/NIPsContactTable.pdf',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='DATA_USED_FOR',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='http://www.pops.int/documents/implementation/nips/submissions/default.htm',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='DATA_USED_FOR_URL',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='http://www.pops.int/documents/implementation/nips/submissions/default.htm',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';	
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='DATE_COMMENTS',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='For Member States that acceeded to the EU on 1 January 2007 (Bulgaria, Romania) the reporting concerning the period 2004-2006 is voluntary.',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='DESCRIPTION',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Water quality data in transitional, coastal and marine waters. Includes data on nutrients, organic matter, chlorophyll-a, hazardous substances and general physico-chemical parameters in water, sediment and biota.',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='EEA_CORE',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='0',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';	
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='EEA_PRIMARY',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='0',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='FIRST_REPORTING',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2005-10-31',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='FK_DELIVERY_COUNTRY_IDS',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE=',34,36,28,',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='FK_SOURCE_ID',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='1',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='FLAGGED',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='0',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='FORMAT_NAME',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Transmission of Information questionnaire',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='LAST_HARVESTED',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2017-11-06 10:14:35',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='LAST_UPDATE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2007-06-29',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='LOCATION_INFO',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='CDR',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='LOCATION_PTR',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='http://cdr.eionet.europa.eu',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='NATIONAL_CONTACT',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Authorised WISE data providers for BWDs',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='NATIONAL_CONTACT_URL',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='http://forum.eionet.europa.eu/x_wise-reporting/library/bathing_directive/reporting_bathing_2011/list-bathing-water-directive-reporters_20120529',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='NEXT_DEADLINE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2013-10-31',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='NEXT_DEADLINE2',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2022-09-30',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='NEXT_REPORTING',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='From bathing season 2007 onwards, MS can choose to report either under Directive 76/160/EEC or Directive 2006/7/EC. Reporting under Directive 2006/7/EC becomes obligatory from the 2012 bathing season on. Visit http://rod.eionet.europa.eu/instruments/609',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='REPORTING_FORMAT',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Information shall be supplied according to Article 17 of the Directive and Commission Decision 98/184/EC of 25 February 1998 concerning a questionnaire for Member States'' reports on the implementation of Council Directive 94/67/EC on the incineration of hazardous waste (implementation of Council Directive 91/692/EEC)',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='REPORT_FORMAT_URL',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Council Directive (EU) 2015/652 of 20 April 2015 laying down calculation methods and reporting requi',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='REPORT_FREQ',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='annually',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';	
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='REPORT_FREQ_DETAIL',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='31 September',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='REPORT_FREQ_MONTHS',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='12',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='RESPONSIBLE_ROLE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='eionet-nrc-waterquality',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='RESPONSIBLE_ROLE_SUF',
	OPERATION='U',
	QUOTES='n',
	P_KEY='n',
	VALUE='1',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='TERMINATE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='N',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='TITLE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='Fuel Quality Directive Article 7a',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='VALID_SINCE',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2018-07-15',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519895729320,
	TAB='T_OBLIGATION',
	COL='VALID_TO',
	OPERATION='U',
	QUOTES='y',
	P_KEY='n',
	VALUE='2014-12-30',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	
INSERT INTO T_UNDO SET
	UNDO_TIME=1519714167727,
	TAB='T_SOURCE',
	COL='PK_SOURCE_ID',
	OPERATION='D',
	QUOTES='n',
	P_KEY='y',
	VALUE='1',
	SUB_TRANS_NR=0,
	SHOW_OBJECT='y';
	